name=input("NAme:")
age=input("Age:")
color=input("Colour:")
actor=input("Actor:")
person_type=input("Person:")
adventure=input("Adventure:")
look=input("Look:")
print(f"Hi! My name is  {name}! I am {age} years old.I like {color} colour. My favorite actor is {actor}. You are an {person_type} person. I love {adventure}. I look {look}." )
print("h")